spring.application.name=auth-service


spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Enable DEBUG logging for Spring Security
logging.level.org.springframework.security=DEBUG


jwt.secret=2sVJHh3NfGTsYvXqBdQkUtGFyFBN5bl6MQTeIQ0D0e8=
jwt.expiration=3600000